export const CART_ADD_ITEM = 'CART_ADD_ITEM';
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM';
export const CART_SAVE_SHIPPING = 'CART_SAVE_SHIPPING';
export const CART_SAVE_PAYMENT = 'CART_SAVE_PAYMENT';

export const CART_BASKET_REQUEST = 'CART_BASKET_REQUEST';
export const CART_BASKET_SUCCESS = 'CART_BASKET_SUCCESS';
export const CART_BESKET_FAIL = 'CART_BESKET_FAIL';